### ISSUE TITLE
Formatting issue on SMS REST API overview page 

### ISSUE THREAD

**Issue by brolaugh** [sinch/docs#19]
On [this](https://developers.sinch.com/docs/sms-rest) page I'm getting the following (I assume) formatting error which I've highlighted in multiple colors.

![image](https://user-images.githubusercontent.com/9987193/68841572-20647580-06c5-11ea-93da-cbe4f7e1c423.png)

**Comment by davidmarquis** [comment]
Thanks for making it obvious with 3-coloured glitter :)

I don't think ReadMe supports commenting out sections of contents this way. What were you looking to achieve exactly?

**Comment by davidmarquis** [comment]
Oh sorry, I looked at the history and you're not the one that has introduced this change, you're just reporting it. 
@spacedsweden you seem to have introduced this change in content. Were you looking to remove the contents? There should be no need for commenting out sections of contents since we're versioning everything.

**Comment by brolaugh** [comment]
This appears to have been fixed in 70a22af6de17fa0810cd61548658e1a49f0349d6 those changes haven't been published yet.

**Comment by brolaugh** [comment]
Closing issue since the entire REST API section appears to be a single page now with the issue not existing anymore.
